import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Provider from './Provider'
import { SavedPinsProvider } from './utils/SavedPinsContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SavedPinsProvider>
        <Provider>
          <body className={inter.className}>
            <div className='flex flex-col gap-2'>
              <div className='fixed z-[1000] w-full bg-white'>
                <Header />
              </div>
              <div className='mt-[70px]'>
                {children}
              </div>
            </div>
          </body>
        </Provider>
      </SavedPinsProvider>

    </html>
  )
}
